[build]
  command = "vite build"
  publish = "dist/client"
[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "application/manifest+json"