/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ComecarRouteImport } from './routes/comecar'
import { Route as ConfiguracaoRouteImport } from './routes/configuracao'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CriancasChildIdRouteImport } from './routes/criancas.$childId'
import { Route as CriancasChildIdIndexRouteImport } from './routes/criancas.$childId.index'
import { Route as CriancasChildIdAvatarRouteImport } from './routes/criancas.$childId.avatar'
import { Route as CriancasChildIdConfiguracaoRouteImport } from './routes/criancas.$childId.configuracao'
import { Route as CriancasChildIdDiarioRouteImport } from './routes/criancas.$childId.diario'
import { Route as CriancasChildIdEstrelasRouteImport } from './routes/criancas.$childId.estrelas'
import { Route as CriancasChildIdHorariosRouteImport } from './routes/criancas.$childId.horarios'
import { Route as CriancasChildIdImprimirRouteImport } from './routes/criancas.$childId.imprimir'
import { Route as CriancasChildIdPassosRouteImport } from './routes/criancas.$childId.passos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ComecarRoute = ComecarRouteImport.update({
  id: '/comecar',
  path: '/comecar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracaoRoute = ConfiguracaoRouteImport.update({
  id: '/configuracao',
  path: '/configuracao',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CriancasChildIdRoute = CriancasChildIdRouteImport.update({
  id: '/criancas/$childId',
  path: '/criancas/$childId',
  getParentRoute: () => rootRouteImport,
} as any)
const CriancasChildIdIndexRoute = CriancasChildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CriancasChildIdRoute,
} as any)
const CriancasChildIdAvatarRoute = CriancasChildIdAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => CriancasChildIdRoute,
} as any)
const CriancasChildIdConfiguracaoRoute =
  CriancasChildIdConfiguracaoRouteImport.update({
    id: '/configuracao',
    path: '/configuracao',
    getParentRoute: () => CriancasChildIdRoute,
  } as any)
const CriancasChildIdDiarioRoute = CriancasChildIdDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => CriancasChildIdRoute,
} as any)
const CriancasChildIdEstrelasRoute = CriancasChildIdEstrelasRouteImport.update({
  id: '/estrelas',
  path: '/estrelas',
  getParentRoute: () => CriancasChildIdRoute,
} as any)
const CriancasChildIdHorariosRoute = CriancasChildIdHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => CriancasChildIdRoute,
} as any)
const CriancasChildIdImprimirRoute = CriancasChildIdImprimirRouteImport.update({
  id: '/imprimir',
  path: '/imprimir',
  getParentRoute: () => CriancasChildIdRoute,
} as any)
const CriancasChildIdPassosRoute = CriancasChildIdPassosRouteImport.update({
  id: '/passos',
  path: '/passos',
  getParentRoute: () => CriancasChildIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/comecar': typeof ComecarRoute
  '/configuracao': typeof ConfiguracaoRoute
  '/entrar': typeof EntrarRoute
  '/criancas/$childId': typeof CriancasChildIdRouteWithChildren
  '/criancas/$childId/avatar': typeof CriancasChildIdAvatarRoute
  '/criancas/$childId/configuracao': typeof CriancasChildIdConfiguracaoRoute
  '/criancas/$childId/diario': typeof CriancasChildIdDiarioRoute
  '/criancas/$childId/estrelas': typeof CriancasChildIdEstrelasRoute
  '/criancas/$childId/horarios': typeof CriancasChildIdHorariosRoute
  '/criancas/$childId/imprimir': typeof CriancasChildIdImprimirRoute
  '/criancas/$childId/passos': typeof CriancasChildIdPassosRoute
  '/criancas/$childId/': typeof CriancasChildIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/comecar': typeof ComecarRoute
  '/configuracao': typeof ConfiguracaoRoute
  '/entrar': typeof EntrarRoute
  '/criancas/$childId/avatar': typeof CriancasChildIdAvatarRoute
  '/criancas/$childId/configuracao': typeof CriancasChildIdConfiguracaoRoute
  '/criancas/$childId/diario': typeof CriancasChildIdDiarioRoute
  '/criancas/$childId/estrelas': typeof CriancasChildIdEstrelasRoute
  '/criancas/$childId/horarios': typeof CriancasChildIdHorariosRoute
  '/criancas/$childId/imprimir': typeof CriancasChildIdImprimirRoute
  '/criancas/$childId/passos': typeof CriancasChildIdPassosRoute
  '/criancas/$childId': typeof CriancasChildIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/comecar': typeof ComecarRoute
  '/configuracao': typeof ConfiguracaoRoute
  '/entrar': typeof EntrarRoute
  '/criancas/$childId': typeof CriancasChildIdRouteWithChildren
  '/criancas/$childId/avatar': typeof CriancasChildIdAvatarRoute
  '/criancas/$childId/configuracao': typeof CriancasChildIdConfiguracaoRoute
  '/criancas/$childId/diario': typeof CriancasChildIdDiarioRoute
  '/criancas/$childId/estrelas': typeof CriancasChildIdEstrelasRoute
  '/criancas/$childId/horarios': typeof CriancasChildIdHorariosRoute
  '/criancas/$childId/imprimir': typeof CriancasChildIdImprimirRoute
  '/criancas/$childId/passos': typeof CriancasChildIdPassosRoute
  '/criancas/$childId/': typeof CriancasChildIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/comecar'
    | '/configuracao'
    | '/entrar'
    | '/criancas/$childId'
    | '/criancas/$childId/avatar'
    | '/criancas/$childId/configuracao'
    | '/criancas/$childId/diario'
    | '/criancas/$childId/estrelas'
    | '/criancas/$childId/horarios'
    | '/criancas/$childId/imprimir'
    | '/criancas/$childId/passos'
    | '/criancas/$childId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/comecar'
    | '/configuracao'
    | '/entrar'
    | '/criancas/$childId/avatar'
    | '/criancas/$childId/configuracao'
    | '/criancas/$childId/diario'
    | '/criancas/$childId/estrelas'
    | '/criancas/$childId/horarios'
    | '/criancas/$childId/imprimir'
    | '/criancas/$childId/passos'
    | '/criancas/$childId'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/comecar'
    | '/configuracao'
    | '/entrar'
    | '/criancas/$childId'
    | '/criancas/$childId/avatar'
    | '/criancas/$childId/configuracao'
    | '/criancas/$childId/diario'
    | '/criancas/$childId/estrelas'
    | '/criancas/$childId/horarios'
    | '/criancas/$childId/imprimir'
    | '/criancas/$childId/passos'
    | '/criancas/$childId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ComecarRoute: typeof ComecarRoute
  ConfiguracaoRoute: typeof ConfiguracaoRoute
  EntrarRoute: typeof EntrarRoute
  CriancasChildIdRoute: typeof CriancasChildIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comecar': {
      id: '/comecar'
      path: '/comecar'
      fullPath: '/comecar'
      preLoaderRoute: typeof ComecarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracao': {
      id: '/configuracao'
      path: '/configuracao'
      fullPath: '/configuracao'
      preLoaderRoute: typeof ConfiguracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criancas/$childId': {
      id: '/criancas/$childId'
      path: '/criancas/$childId'
      fullPath: '/criancas/$childId'
      preLoaderRoute: typeof CriancasChildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criancas/$childId/': {
      id: '/criancas/$childId/'
      path: '/'
      fullPath: '/criancas/$childId/'
      preLoaderRoute: typeof CriancasChildIdIndexRouteImport
      parentRoute: typeof CriancasChildIdRoute
    }
    '/criancas/$childId/avatar': {
      id: '/criancas/$childId/avatar'
      path: '/avatar'
      fullPath: '/criancas/$childId/avatar'
      preLoaderRoute: typeof CriancasChildIdAvatarRouteImport
      parentRoute: typeof CriancasChildIdRoute
    }
    '/criancas/$childId/configuracao': {
      id: '/criancas/$childId/configuracao'
      path: '/configuracao'
      fullPath: '/criancas/$childId/configuracao'
      preLoaderRoute: typeof CriancasChildIdConfiguracaoRouteImport
      parentRoute: typeof CriancasChildIdRoute
    }
    '/criancas/$childId/diario': {
      id: '/criancas/$childId/diario'
      path: '/diario'
      fullPath: '/criancas/$childId/diario'
      preLoaderRoute: typeof CriancasChildIdDiarioRouteImport
      parentRoute: typeof CriancasChildIdRoute
    }
    '/criancas/$childId/estrelas': {
      id: '/criancas/$childId/estrelas'
      path: '/estrelas'
      fullPath: '/criancas/$childId/estrelas'
      preLoaderRoute: typeof CriancasChildIdEstrelasRouteImport
      parentRoute: typeof CriancasChildIdRoute
    }
    '/criancas/$childId/horarios': {
      id: '/criancas/$childId/horarios'
      path: '/horarios'
      fullPath: '/criancas/$childId/horarios'
      preLoaderRoute: typeof CriancasChildIdHorariosRouteImport
      parentRoute: typeof CriancasChildIdRoute
    }
    '/criancas/$childId/imprimir': {
      id: '/criancas/$childId/imprimir'
      path: '/imprimir'
      fullPath: '/criancas/$childId/imprimir'
      preLoaderRoute: typeof CriancasChildIdImprimirRouteImport
      parentRoute: typeof CriancasChildIdRoute
    }
    '/criancas/$childId/passos': {
      id: '/criancas/$childId/passos'
      path: '/passos'
      fullPath: '/criancas/$childId/passos'
      preLoaderRoute: typeof CriancasChildIdPassosRouteImport
      parentRoute: typeof CriancasChildIdRoute
    }
  }
}

interface CriancasChildIdRouteChildren {
  CriancasChildIdAvatarRoute: typeof CriancasChildIdAvatarRoute
  CriancasChildIdConfiguracaoRoute: typeof CriancasChildIdConfiguracaoRoute
  CriancasChildIdDiarioRoute: typeof CriancasChildIdDiarioRoute
  CriancasChildIdEstrelasRoute: typeof CriancasChildIdEstrelasRoute
  CriancasChildIdHorariosRoute: typeof CriancasChildIdHorariosRoute
  CriancasChildIdImprimirRoute: typeof CriancasChildIdImprimirRoute
  CriancasChildIdPassosRoute: typeof CriancasChildIdPassosRoute
  CriancasChildIdIndexRoute: typeof CriancasChildIdIndexRoute
}

const CriancasChildIdRouteChildren: CriancasChildIdRouteChildren = {
  CriancasChildIdAvatarRoute: CriancasChildIdAvatarRoute,
  CriancasChildIdConfiguracaoRoute: CriancasChildIdConfiguracaoRoute,
  CriancasChildIdDiarioRoute: CriancasChildIdDiarioRoute,
  CriancasChildIdEstrelasRoute: CriancasChildIdEstrelasRoute,
  CriancasChildIdHorariosRoute: CriancasChildIdHorariosRoute,
  CriancasChildIdImprimirRoute: CriancasChildIdImprimirRoute,
  CriancasChildIdPassosRoute: CriancasChildIdPassosRoute,
  CriancasChildIdIndexRoute: CriancasChildIdIndexRoute,
}

const CriancasChildIdRouteWithChildren = CriancasChildIdRoute._addFileChildren(
  CriancasChildIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ComecarRoute: ComecarRoute,
  ConfiguracaoRoute: ConfiguracaoRoute,
  EntrarRoute: EntrarRoute,
  CriancasChildIdRoute: CriancasChildIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
